### ISSUE TITLE
Game hangs when equipping items

### ISSUE THREAD

**Issue by robrigo** [bada-studio/knights_contract#15]
Playing on the latest version of Chrome:  68.0.3440.106

The game loads infinitely when trying to equip an item. 

<img width="431" alt="screen shot 2018-08-20 at 9 14 39 am" src="https://user-images.githubusercontent.com/590263/44342696-d2c57280-a459-11e8-8a75-d8b58f36e87e.png">

**Comment by robrigo** [comment]
Same deal when you try to pattach items:

<img width="435" alt="screen shot 2018-08-20 at 9 47 33 am" src="https://user-images.githubusercontent.com/590263/44344221-1a4dfd80-a45e-11e8-8bde-5c6ba5b1a37a.png">

**Comment by mj-raindays** [comment]
It's fixed if it takes too long (more than 8sec) it shows error alert.
And there are more available nodes, 
if you are nearby one of that node, you can play the game more faster
