### ISSUE TITLE
Make seed number hard to guess.

### ISSUE THREAD

**Issue by mj-raindays** [bada-studio/knights_contract#67]
There is some random-seed seeking attack.
We think that one of player's account(v.io) tries to buy materials and craft high-quality item.
This account could not change the value but maybe can guess what percent will be applied this time.

To make impossible to calculate the random value, we use these value for the seed:
- [x] Custom transaction hash 
- [x] Checksum
- [x] Last block's hash
- [x] And others

**Comment by mj-raindays** [comment]
We have 'CONTRACT BUG BOUNTY' up to 100 EOS.
If you found a bug or security issue on our contract, please contact us.

**Comment by ChachiQ** [comment]
i cracked your random-seed. If I told you , could get the 200 EOS?
